Models/CompanyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterviewPractice.Sites.MVC.Models
{
    public class CompanyModel
    {
        public CompanyModel()
        {
            Companies = new List<Company>();
        }
        public List<Company> Companies { get; set; }
    }

    public class Company
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Name { get; set; }
        public List<Employee> Employees { get; set; }
    }
}

Models/EmployeeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterviewPractice.Sites.MVC.Models
{
    public class EmployeeModel
    {
        public EmployeeModel()
        {
            Employees = new List<Employee>();
        }

        public List<Employee> Employees { get; set; }
    }

    public class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
    }
}

Controllers/CompanyController.cs
using InterviewPractice.Sites.MVC.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace InterviewPractice.Sites.MVC.Controllers
{
    public class CompanyController : Controller
    {
        private ServiceReference1.CompanyServiceClient companyService = new ServiceReference1.CompanyServiceClient();

        [Route("Company/{id}")]
        public ActionResult Index(int id)
        {
            var employees = companyService.GetEmployeesForACompany(id);
            var employeeModel = new EmployeeModel();
            foreach (var e in employees)
            {
                employeeModel.Employees.Add(new Employee() { BirthDate = e.Birthday, FirstName = e.FirstName, Id=e.Id, LastName=e.LastName});
            }
            return View(employeeModel);
        }
    }
}

Controllers/EmployeeController.cs
using InterviewPractice.Sites.MVC.Models;
using System;
using System.Web.Mvc;

namespace InterviewPractice.Sites.MVC.Controllers
{
    public class EmployeeController : Controller
    {
        private ServiceReference1.CompanyServiceClient companyService = new ServiceReference1.CompanyServiceClient();
        [Route("Employee/{id}")]
        public ActionResult Index(int id)
        {
            var employee = companyService.GetEmployee(id);
            var employeeModel = new Employee() { Id = employee.Id, LastName = employee.LastName, FirstName = employee.FirstName, BirthDate =employee.Birthday};
            return View(employeeModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InterviewPractice.Sites.MVC.Helpers;
using System.ServiceModel;
using InterviewPractice.Sites.MVC.Models;
namespace InterviewPractice.Sites.MVC.Controllers
{
    public class HomeController : Controller
    {
        private ServiceReference1.CompanyServiceClient companyService = new ServiceReference1.CompanyServiceClient();

        public ActionResult Index()
        {
            
            var allCompanies = companyService.GetAllCompanies();

            var companyModel = new CompanyModel();
            foreach (var company in allCompanies)
            {
                companyModel.Companies.Add(new Company { City = company.City, Id = company.Id, Name = company.Name, State = company.State });
            }


            return View(companyModel);
        }
    }
}

Views/Company/Index.cshtml
@model InterviewPractice.Sites.MVC.Models.EmployeeModel

@{
    ViewBag.Title = "Index";
}

<div>
    @foreach(var e in Model.Employees)
    {
        <div>
            @Html.ActionLink(e.LastName + "," + e.FirstName, e.Id.ToString(), "Employee" ) 
        </div>
    }
</div>

Views/Employee/Index.cshtml
@model InterviewPractice.Sites.MVC.Models.Employee

<div>
    <ul>
        <li> @Model.FirstName</li>
        <li> @Model.LastName</li>
        <li> @Model.BirthDate</li>
    </ul>
</div>

Views/Home/Index.cshtml
@model InterviewPractice.Sites.MVC.Models.CompanyModel
@{
    ViewBag.Title = "Home Page";
}
<div class="home-container">
    @foreach (var item in Model.Companies)
    {
        <div>
            @Html.ActionLink(item.Name, item.Id.ToString(), "Company")
        </div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Company Admin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>